config/routes.rb
require 'sidekiq/web'

Agra::Application.routes.draw do

  pulse # for monitoring

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'users/omniauth_callbacks'} do
    match '/users/auth/facebook/setup', to: 'users/omniauth_callbacks#setup'
  end

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'home#index'

  mount FacebookShareWidget::Engine => "/widget"

  match 'intro' => 'home#intro', as: :intro
  match 'about_us' => 'home#about_us', as: :about_us
  match 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  match 'tos' => 'home#tos', as: :tos
  match 'community' => 'home#community', as: :community
  match 'media' => 'home#media', as: :media

  get 'account' => 'users#edit'
  put 'account' => 'users#update'
  put 'account/update_password' => 'users#update_password'

  devise_scope :user do
    get 'registrations/complete' => 'registrations#completing'
    post 'registrations/complete'
  end

  resources :categories, only: [:index, :show]

  match 'admin' => 'admin/admin#index', as: :admin
  namespace :admin do
    resources :petitions, only: [:index] do
      collection do
        get 'search'
        get 'hot'
      end
    end
    resources :organisations
    resources :users, only: [:index, :edit, :update] do
      collection do
        get 'export'
        get 'email'
        get 'jobs'
      end
    end
  end

  resource :org, controller: 'org/organisation', only: [:show, :update] do
    member do
      get 'settings'
    end
    resource :placeholder, controller: 'org/organisation/placeholder', only: [:show, :update]
  end
  namespace :org do
    resources :csv_reports, only: [:show]
    resources :comments, only: [:index] do
       member do
        put 'approve'
        put 'remove'
       end
    end
    resources :petitions, only: [:index, :update, :show] do
      collection do
        get 'search'
        get 'hot'
        get 'flagged'
        get 'moderation_queue'
      end
      resources :signatures, only: [:index, :destroy], controller: 'petitions/signatures' do
        collection do
          get 'email'
        end

        member do
          put 'unsubscribe'
        end
      end
      resource :settings, only: [:show, :update], controller: 'petitions/settings'
      resource :note, only: [:update], controller: 'petitions/note'
      resource :user, only: [:edit, :update], controller: 'petitions/user'
      resources :flags, only: [:index], controller: 'petitions/flags'
      resources :facebook_share_variants, controller: 'petitions/facebook_share_variants'
      resources :comments, only: [:index], controller: 'petitions/comments' do
        member do
          put 'approve'
          put 'remove'
        end
      end
    end
    resources :categories, except: ['show']
    resources :emails, only: [:index, :show, :update] do
      collection do
        get 'moderation'
      end
    end

    resources :landing_pages

    resources :efforts do
      resources :leaders, controller: 'efforts/leaders', only: [:show, :destroy]
      resources :petitions, controller: 'efforts/petitions', only: [] do
        member do
          get 'check'
          post 'move'
          put 'note'
        end
      end

      resources :imports, controller: 'efforts/imports', only: [:new, :create]
      resources :targets, controller: 'efforts/targets', only: [:new, :create, :index, :edit, :update] do
        collection do
          get 'find'
          post 'add'
          put  'add_collection'
        end



        member {delete 'remove'}
      end
    end

    resources :groups, :path => 'partnerships'do
      resources :invitations, controller: 'groups/invitations', only: [:create]
      resources :users, controller: 'groups/users'
      resources :petitions, controller: 'groups/petitions', only: [] do
        member do
          get 'check'
          post 'move'
        end
      end
    end
    resources :email_white_lists, only: [:new, :create]

    namespace :contents do
      resources :stories
      resources :templates
    end

    resources :contents do
      collection do
        get 'migrate'
        post 'import'
        get 'export'
      end
    end

    resources :members, only: [:show, :index] do
      collection do
        get 'email'
      end
    end

    resources :users do
      collection do
        get 'export'
        get 'email'
        get 'bad_postcodes'
      end
    end

    resource :query, only: [:new, :create]
    resources :exports, only: [:index] do
      collection do
        get 'petitions'
        get 'signatures'
        get 'members'
      end
    end
  end

  match '/petition/new' => 'petitions#new', as: :new_petition
  get '/p/:id' => 'petitions/view#show_alias', as: :petition_alias

  namespace :petitions do
    resources :near, only: [:new, :index] do
      member do
        get 'embed'
        get 'iframe'
      end
    end
    resources :locations, only: [:index]
    resources :countries, only: [:show] do
      member do
        get 'embed'
        get 'iframe'
      end
    end
  end

  resources :petitions, except: [:new, :show] do
    collection do
      get 'search'
      get 'landing', to: 'petitions#landing'
    end

    member do
      get 'share'
      get 'launch', to: 'petitions#launching'
      put 'launch'
      get 'thanks', to: 'petitions/view#thanks'
      get 'show', to: 'petitions/view#show'
    end

    resources :facebook_share_variants, controller: 'petitions/facebook_share_variants', only: [:show, :update]
    resources :contacts, controller: 'petitions/contacts', only: [:new, :create]

    resource :categories, controller: 'petitions/categories', only: [:show, :update]

    resource :manage, controller: 'petitions/manage', only: [:edit, :update, :show] do
      get 'download_letter'
      get 'download_form'
      put 'cancel'
      put 'activate'
      get 'deliver'
      get 'offline'
      post 'contact_admin'
      post 'check_alias'
      post 'update_alias'
      get 'training'
    end

    resources :admins, controller: 'petitions/admins', only: [:new, :create, :show, :destroy]

    resources :signatures, controller: 'petitions/signatures', only: [:index, :create, :destroy] do
      collection do
        get 'manual_input', to: 'petitions/signatures#manual_input'
        post 'manual_input', to: 'petitions/signatures#save_manual_input'
      end
      member do
        get 'confirm_destroy'
        get 'unsubscribing'
        put 'unsubscribe'
      end
    end

    resources :comments, controller: 'petitions/comments', only: [:index, :show] do
      resources :flags, controller: 'petitions/comments/flags', only: [:new, :create]
      member do
        post 'create', :as => :create
        put 'like'
      end
    end

    resources :emails, controller: 'petitions/emails', only: [:new, :create] do
      collection do
        post 'test', to: 'petitions/emails#test'
      end
    end

    resources :flags, controller: 'petitions/petition_flags', only: [:create] do
    end
  end

  resources :shares, only:[:show] do
    collection { get 'lookup' }
  end

  resources :efforts, only: [:show] do
    member { get 'locations' }
    resources :petitions, controller: 'efforts/petitions', only: [:new, :edit, :update] do
      member do
        get 'leading'
        put 'lead'
        get 'training'
        put 'train'
      end
    end
    resources :near, controller: 'efforts/near', only: [:new, :index]
  end

  resources :groups, only: [:index, :show], :path => 'partnerships' do
    resources :unsubscribes, controller: 'groups/unsubscribes', only: [:show, :update]
    resources :invitations, controller: 'groups/invitations', only: [:show, :update]
    resources :petitions, controller: 'groups/petitions', only: [:index, :new] do
      collection do
        get 'hot'
      end
    end
    resource  :manage, controller: 'groups/manage', only: [:index, :show] do
      get 'export'
    end
    resources :emails, controller: 'groups/emails', only: [:new, :create] do
      collection do
        post 'test', to: 'groups/emails#test'
      end
    end
  end

  match 'cached_url/*uri' => 'cached_url#retrieve', as: :cached_embedly

  get 'errors/pingdom'   #makes sure the app is up.
  get 'errors/exception' #convenient way to test if exception notification is working
  get 'errors/streaming' # test for streaming responses.

  match '/404', to: 'errors#not_found'
  match '/500', to: 'errors#internal_server_error'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, :all

  def index
    @featured_stories = Story.featured_stories(current_organisation)
    @featured_petitions = Petition.featured_homepage_petitions(current_organisation)
  end

  def intro
  end

  def about_us
  end

  def tos
  end

  def privacy_policy
  end

end

app/views/home/_campaign.html.haml
%li
  %a.thumbnail{ href: petition_path(campaign) }
    = image_content(entity: campaign)
    .caption
      %h5= campaign.title

app/views/home/_featured_effort.html.haml
.row
  .span1
    = "&nbsp;".html_safe
  .span4
    %a{ href: effort_path(effort) }
      .petition-image-wrapper
        - unless effort.image_file_name.blank?
          .effort-image
            =image_tag effort.image.url(:hero)
        - else
          .effort-image
            =image_tag "image-placeholder-home.png"
      .effort-progress
        = render partial: "efforts/near/effort_progress", locals: { effort: effort, no_text: true }
.row
  .span1
    .effort-signatures
      %span.number= number_with_delimiter(effort.cached_signatures_size)
      %br
      of
      %span.strong= number_with_delimiter(effort.goal)
      %br
      signatures
  .span4
    %a{ href: effort_path(effort) }
      .effort-title
        %h3=effort.title

app/views/home/_featured_item.haml
.featured-petition
  .row
    .span1
      = "&nbsp;".html_safe
    .span4
      %a{ href: url_for(featured_item) }
        .petition-image-wrapper
          - unless featured_item.image_file_name.blank?
            .petition-image
              = image_tag featured_item.image.url(:hero)
          - else
            .petition-image
              = image_tag "image-placeholder-home.png"
        .petition-progress
          = render :partial => "petitions/view/petition_progress",
                   :locals => { petition: featured_item, no_text: true }
  .row
    .span1
      .petition-signatures
        %span.number= number_with_delimiter(featured_item.cached_signatures_size)
        %br
        of
        %span.strong= number_with_delimiter(featured_item.goal)
        %br
        signatures
    .span4
      %a{ href: url_for(featured_item) }
        .petition-title
          %h3=featured_item.title
        - if featured_item.respond_to?(:why)
          .petition-why
            =featured_item.why

app/views/home/_featured_petition.haml
.featured-petition
  .row
    .span1
      = "&nbsp;".html_safe
    .span4
      %a{ href: petition_path(featured_petition) }
        .petition-image-wrapper
          - unless featured_petition.image_file_name.blank?
            .petition-image
              =image_tag featured_petition.image.url(:hero)
          - else
            .petition-image
              =image_tag "image-placeholder-home.png"
        .petition-progress
          = render :partial => "petitions/view/petition_progress",
                   :locals => { petition: featured_petition, no_text: true }
  .row
    .span1
      .petition-signatures
        %span.number= number_with_delimiter(featured_petition.cached_signatures_size)
        %br
        of
        %span.strong= number_with_delimiter(featured_petition.goal)
        %br
        signatures
    .span4
      %a{ href: petition_path(featured_petition) }
        .petition-title
          %h3=featured_petition.title
        .petition-why
          =featured_petition.why

app/views/home/_homepage_map_widget.haml
- content_for :head do
  %script{ type: "text/javascript", src:"http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"}
  = javascript_include_tag 'location'
.row
  .span8{:style => 'width: 590px'}
    .inner-shadow
      #location-map{'data-default-bounds' => current_organisation.default_map_bounds.to_json}
    .span6.search-area.pull-left
      %form.big-efforts-search.effort-location-search{ action: petitions_near_index_path, method: 'GET' }
        #efforts-near-container.near-effort-search.query-container.span8.offset1{'data-organisation-country' => current_organisation.settings[:country]}
          = render :partial => 'petitions/near/search_container', :locals => {:submit_text => 'Find Petitions'}
      %br
      #location-categories
        .title Filter by category
        = form_tag new_petitions_near_path, :method => 'GET' do
          = radio_button_tag :category, '', params[:category].blank?
          = label :category, '', 'All'
          - current_organisation.categories.each do |category|
            = radio_button_tag :category, category.slug, params[:category] == category.slug
            = label :category, category.slug, category.name

app/views/home/_petition_list_item.haml
%li
  %a{ href: petition_path(petition_list_item) }
    - unless petition_list_item.image_file_name.blank?
      .list-item-image
        =image_tag petition_list_item.image.url
    - else
      .list-item-image
        =image_tag "image-placeholder-home.png"
  .list-item-desc-box
    .list-item-desc
      %span.list-item-title= petition_list_item.title
      %span.list-item-why= petition_list_item.why

app/views/home/_stories_carousel.haml
- content_for :head do
  = javascript_include_tag "jquery.jcarousel.min"

%ul.petition_carousel#petition_carousel
  - @featured_stories.each do |story|
    %li
      .list-item-image
        = link_to story.link.present? ? story.link : "#" do
          = image_tag story.image.url(:hero)
      .list-item-desc-box
        .list-item-desc
          %span.list-item-title= story.title
          %span.list-item-why= story.content

:javascript
  $(function() {
    $('#petition_carousel').jcarousel({
      wrap: 'both',
      scroll: 1,
      start: 2,
      itemVisibleInCallback: {
        onBeforeAnimation: function(carousel, item, idx, state) {
          $('.list-item-desc-box', item).show();
        },
        onAfterAnimation: function(carousel, item, idx, state) {

        }
      },
      itemVisibleOutCallback: {
        onBeforeAnimation: function(carousel, item, idx, state) {
          $('.list-item-desc-box', item).hide();
        },
        onAfterAnimation: function(carousel, item, idx, state) {

        }
      },
      itemFallbackDimension: 590
    });
  });

app/views/home/about_us.haml
- title "About Us"

.row
  .span8.offset2
    =cf('about_us')

app/views/home/community.haml
- title "Community"

.row
  .span8.offset2
    = cf('community')

app/views/home/index.haml
/ facebook meta tags
- content_for :head do
  %meta{property: "og:title", content: "#{current_organisation.name}"}
  %meta{property: "og:image", content:"#{request.protocol}#{request.host_with_port}/assets/organisations/#{current_organisation.slug}/logo_share.png"}
- content_for :before_content do

  .home-banner
    .overlay-left
    .overlay-right

    .wordings
      %h1.highlight
        =cf('homepage_headline')
      - if user_signed_in? || session[:can_create_campaign] || current_organisation.skip_white_list_check?
        = link_to new_petition_path(:source => 'homepage'), class: "btn-start-petition" do
          %span.text Start a campaign
        .subtle We'll connect you to help and tools every step of the way.
      - else
        = link_to "", intro_path, class: "btn-register-your-interest"
      .about-and-contact
        = link_to "About Us", about_us_path

    .spotlight
      = render partial: 'stories_carousel'

.row
  .span5
    .featured-petitions-logo
    .featured-petitions
      - cache("home_index_#{current_organisation.id}_featured", expires_in: 1.minute) do
        = render partial: "home/featured_item", collection: @featured_petitions
    .featured-more
      = link_to categories_path, class: "btn btn-primary" do
        More Campaigns

  .span6.offset1
    .explain-site
      =cf('homepage_explainer')

:javascript
  function adjustOverlay() {
    var left = $(".spotlight").position().left + 590;
    var width = $(window).width() - $(".spotlight").position().left - 590;

    if (width <= 0) {
      $('.overlay-right').width(0);
    }
    else {
      $('.overlay-right').offset({ left: left });
      $('.overlay-right').width(width);
    }
  }

  $(function() {
    adjustOverlay();

    $(window).resize(function() {
      adjustOverlay();
    });
  });

app/views/home/intro.haml
.row
  .span8
    = title "Winning Your Campaign"

    %h3
      Start a Petition

    %p
      Text about petition and the theory of change.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.

    %h3
      Gather Support

    %p
      How the tactics these tools enable will help you gather support.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.


    %h3
      Win


    %p
      The hard work you'll need to do to actually win. Petitions are not enough.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consectetur orci mollis arcu dapibus blandit iaculis urna sodales. Praesent convallis nunc lectus, in interdum ligula. Fusce ac neque arcu.

    = link_to "Get Started!", new_petition_path, :class => 'arrow-link'

  .span4
    %h3
      Resources

    %h4
      Links to more resources.

app/views/home/media.haml
- title "Media"

.row
  .span8.offset2
    =cf('media')

app/views/home/privacy_policy.haml
- title "Privacy Policy"

.row
  .span8.offset2
    = cf('privacy_policy')

app/views/home/tos.haml
- title "Terms of Service"

.row
  .span8.offset2
    =cf('tos')